SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+07:00";
SET FOREIGN_KEY_CHECKS = 0;

START TRANSACTION;

-- DROP ALL TABLES (REVERSE FK ORDER)
DROP TABLE IF EXISTS TicketUserRequest;
DROP TABLE IF EXISTS TicketCategory;
DROP TABLE IF EXISTS TicketFollower;
DROP TABLE IF EXISTS TicketHistory;
DROP TABLE IF EXISTS TicketComments;
DROP TABLE IF EXISTS TicketAssignee;
DROP TABLE IF EXISTS Ticket;

DROP TABLE IF EXISTS SpecialistScope;
DROP TABLE IF EXISTS SpecialistProfile;

DROP TABLE IF EXISTS DraftTicketCategory;
DROP TABLE IF EXISTS DraftTicketAssignee;
DROP TABLE IF EXISTS DraftTicketUserRequest;
DROP TABLE IF EXISTS DraftTicket;

DROP TABLE IF EXISTS UserRequest;
DROP TABLE IF EXISTS Users;

-- CREATE TABLES

CREATE TABLE Users(
	email VARCHAR(64) PRIMARY KEY,
	name VARCHAR(128),
	password_hash VARCHAR(255),
	google_id VARCHAR(255),
	perm INT DEFAULT 1
);

CREATE TABLE UserRequest(
	id INT AUTO_INCREMENT PRIMARY KEY,
	userEmail VARCHAR(64) NOT NULL,
	requestContents VARCHAR(2048),
	tracking_token VARCHAR(64) UNIQUE,
	createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (userEmail) REFERENCES Users(email) ON DELETE CASCADE
);

CREATE TABLE SpecialistProfile(
	userEmail VARCHAR(64) PRIMARY KEY,
	contact VARCHAR(64),
	FOREIGN KEY (userEmail) REFERENCES Users(email) ON DELETE CASCADE
);

CREATE TABLE SpecialistScope(
	userEmail VARCHAR(64),
	scopeTag VARCHAR(64),
	PRIMARY KEY (userEmail, scopeTag),
	FOREIGN KEY (userEmail) REFERENCES Users(email) ON DELETE CASCADE
);

CREATE TABLE Ticket(
	id INT AUTO_INCREMENT PRIMARY KEY,
	requestContents VARCHAR(2048),
	suggestedSolutions VARCHAR(2048),
	title VARCHAR(256),
	status VARCHAR(32) DEFAULT 'draft',
	deadline DATETIME,
	createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
	updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE TicketAssignee(
	ticketID INT,
	assigneeEmail VARCHAR(64),
	PRIMARY KEY (ticketID, assigneeEmail),
	FOREIGN KEY (ticketID) REFERENCES Ticket(id) ON DELETE CASCADE,
	FOREIGN KEY (assigneeEmail) REFERENCES Users(email) ON DELETE CASCADE
);

CREATE TABLE TicketComments(
	id INT AUTO_INCREMENT PRIMARY KEY,
	ticketID INT,
	authorEmail VARCHAR(64),
	text VARCHAR(2048) NOT NULL,
	isInternal BOOLEAN DEFAULT FALSE,
	createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (ticketID) REFERENCES Ticket(id) ON DELETE CASCADE,
	FOREIGN KEY (authorEmail) REFERENCES Users(email) ON DELETE CASCADE
);

CREATE TABLE TicketHistory(
	id INT AUTO_INCREMENT PRIMARY KEY,
	ticketID INT,
	action VARCHAR(128),
	performedBy VARCHAR(64),
	details VARCHAR(2048),
	timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (ticketID) REFERENCES Ticket(id) ON DELETE CASCADE
);

CREATE TABLE TicketFollower(
	ticketID INT,
	userEmail VARCHAR(64),
	PRIMARY KEY (ticketID, userEmail),
	FOREIGN KEY (ticketID) REFERENCES Ticket(id) ON DELETE CASCADE,
	FOREIGN KEY (userEmail) REFERENCES Users(email) ON DELETE CASCADE
);

CREATE TABLE TicketCategory(
	ticketID INT,
	category VARCHAR(32),
	PRIMARY KEY (ticketID, category),
	FOREIGN KEY (ticketID) REFERENCES Ticket(id) ON DELETE CASCADE
);

CREATE TABLE TicketUserRequest(
	ticketID INT,
	userRequestID INT,
	PRIMARY KEY (ticketID, userRequestID),
	FOREIGN KEY (ticketID) REFERENCES Ticket(id) ON DELETE CASCADE,
	FOREIGN KEY (userRequestID) REFERENCES UserRequest(id) ON DELETE CASCADE
);

SET FOREIGN_KEY_CHECKS = 1;
COMMIT;